program: /files1/Yuxuan_Li/failed_demos/Experiments/Robots/PandaReacher_KR_SFD_args.py
name: sweep_KR_SFD
method: grid
metric:
  goal: maximize
  name: old_rewards
parameters:
  exp_k:
    values: [1, 2, 3, 4, 5]
  kernel_bandwidth:
    values: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
  n_s_demos:
    values: [50, 100, 200, 500, 1000]
  n_f_demos:
    values: [50, 100, 200, 500, 1000]
