program: /files1/Yuxuan_Li/failed_demos/Experiments/General_Env/Humanoid/Humanoid_KR_SFD_args.py
name: sweep_KR_SFD
method: grid
metric:
  goal: maximize
  name: old_rewards
parameters:
  exp_k:
    values: [1, 2, 5]
  kernel_bandwidth:
    values: [0.4, 0.5, 0.6, 0.7]
  n_s_demos:
    value: 200
  n_f_demos:
    value: 200
