program: /home/yuxuanli/failed_IRL_new/Maze/update_baselines/BCIRL_reward_test.py
name: sweep_BCIRL
method: grid
metric:
  goal: maximize
  name: Episode Reward
parameters:
  update_timesteps:
    values: [100, 300, 1500, 3000, 4500]
  reward_epochs:
    values: [5, 100, 200]
